name: l10n_app
description: Localization App for Flutter Projects

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  _di_layer:
    path: ./packages/_di_layer
  _presentation_layer:
    path: ./packages/_presentation_layer

  bitsdojo_window: ^0.1.5

  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
