name: _service_layer
description: Service Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer
    
  faker: ^2.0.0
  flutter:
    sdk: flutter
  riverpod: 2.0.0-dev.9

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
