name: _domain_layer
description: Domain Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
    
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  freezed_annotation: ^2.2.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  pubspec_parse: ^1.2.1
  riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6
  tuple: ^2.0.1
  uuid: ^3.0.7
  yaml: ^3.1.1
  yaml_writer: ^1.0.2

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  riverpod_generator: ^1.0.6

flutter:
