name: _data_layer
description: Data Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer
    
  flutter:
    sdk: flutter
    
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2
  path_provider: ^2.0.11    
  riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  objectbox_generator: ^1.6.2
  riverpod_generator: ^1.0.6
      
flutter:
