name: _di_layer
description: DI Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _data_layer:
    path: ../_data_layer
  _domain_layer:
    path: ../_domain_layer
  _presentation_layer:
    path: ../_presentation_layer
    
  flutter:
    sdk: flutter
  riverpod: 2.0.0-dev.9

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
    
flutter:
