name: _presentation_layer
description: Presentation Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer

  bitsdojo_window: 0.1.2
    
  dotted_border: ^2.0.0+2
  extended_text: ^9.1.0
  file_selector: ^0.8.4+3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: 2.0.0-dev.9
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  fonts:
    - family: MaterialSymbolsOutlined
      fonts:
        - asset: fonts/MaterialSymbolsOutlined.ttf
