name: _presentation_layer
description: Presentation Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer

  bitsdojo_window: ^0.1.5
    
  dotted_border: ^2.0.0+3
  extended_text: ^9.1.2
  file_selector: ^0.9.2+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.1.1
  intl: ^0.17.0
  riverpod_annotation: ^1.0.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true

  fonts:
    - family: MaterialSymbolsOutlined
      fonts:
        - asset: fonts/MaterialSymbolsOutlined.ttf
